### ISSUE TITLE
Is it under development?

### ISSUE THREAD

**Issue by mcueto** [imanhodjaev/django-auth0#1]
Hi my friend, i want to know if it's under development yet. If it's not and you need to implement a thing like that in django please tellme, i'm writing something similar for django rest framework.

**Comment by sultaniman** [comment]
@mcueto thank you, I was busy on my main project so today or tomorrow I will try to make a release also I updated project a few moments ago.

**Comment by mcueto** [comment]
@imanhodjaev My idea is get for standards, so i think that all people working around auth0 in django must be unite to get the best standard approach to solve this problem.

i will keep looking your code. And listen, there is not need to run(related to the release), hahahahaha :)

Thanks for your answer. Good weekend

**Comment by sultaniman** [comment]
No problem man, I already made some commits so feel free to review.
