### ISSUE TITLE
Django User Model

### ISSUE THREAD

**Issue by pnovotnak** [imanhodjaev/django-auth0#11]
I'd like to start working on the user model to support the Auth0 backend, and I thought it'd be a good idea to talk before I start work.

I think that https://github.com/stormpath/stormpath-django/blob/master/django_stormpath/models.py would make a reasonably good reference, adding or removing things as required.

What are your thoughts on how it should look?

**Comment by sultaniman** [comment]
@pnovotnak thank you, I think it is a good idea to have a custom user model which can be used as a swappable user model in Django Auth0 integration and if you can contribute I think it would really nice.

**Comment by stev-0** [comment]
@pnovotnak - potentially looking to do something similar. How far did you get with this in the end?

**Comment by pnovotnak** [comment]
To be honest I've pretty much forgotten. Too much going on to work on this--Django projects take a back seat to Golang ones these days.

https://github.com/cyrusbiotechnology/django-auth0/tree/feat/user-model
