### ISSUE TITLE
Create standarized user model?

### ISSUE THREAD

**Issue by mcueto** [imanhodjaev/django-auth0#2]
Hi my friend, what do you think about creating custom models to standarize the Django user model to the normalized user profile in django? https://auth0.com/docs/user-profile/normalized

If you want i create it tomorrow for discussion.

**Comment by sultaniman** [comment]
@mcueto I think it depends on the

```
authParams: {
  scope: 'openid profile'
}
```

thats why I decided to provide a possibility for user to create his own route to handle Auth0 callback.

**Comment by mcueto** [comment]
Ok, thanks for the answer. Good week!
