### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by peterbe** [imanhodjaev/django-auth0#3]
https://pypi.python.org/pypi/django-auth0 is void of release files. :(

**Comment by sultaniman** [comment]
@peterbe I'm sorry for this, can you please update you pip to newer version and try again I had some problems with installation too on `pip==8.1.1`. Also re-uploaded it to pypi registry. Once you check please ping me.

**Comment by peterbe** [comment]
Excellent. It worked. 
I have to use `pip install --no-deps django-auth0` because the requirements forces me up upgrade Django. 

Also, I noticed [the tooling](https://github.com/imanhodjaev/django-auth0/blob/master/setup.py#L36) to make a wheel but it's not appearing on PyPI. Only the tar ball.

**Comment by sultaniman** [comment]
@peterbe thank you very much, I am sorry I forgot about wheel distribution during upload now I did it 👍

**Comment by sultaniman** [comment]
@peterbe if you have suggestions and improvement you're welcome to make PR

**Comment by peterbe** [comment]
My only suggestion is to let travis do the deployment. [For example](https://github.com/peterbe/gg/blob/6ab3464a49f7252ecb3b55eb10f10924de1c3533/.travis.yml#L21).
