### ISSUE TITLE
Auth0Backend does not allow auth to fallback to other auth backends

### ISSUE THREAD

**Issue by brendonjohn** [imanhodjaev/django-auth0#4]
Hey there, thanks for the work you've done on integrating Django with Auth0.

I want to raise a PR to fix this, but want to get your input on my approach before cutting the code.

As I understand, the order of values in `AUTHENTICATION_BACKENDS` for a projects settings is the order that Django will attempt to authenticate a user. If the `Auth0Backend` is used first, you're not able to login to the Django admin. This is because `Auth0Backend` assumes an email will be provided and then raise a Value error.

Instead of raising the `ValueError`, should we `return None` so that the next (if available) backend is used?

**Comment by sultaniman** [comment]
@brendonjohn yes please do it is a good reason for PR we still want users to be able to logged in by other backends. 

Thank you.
